allowBuilds:
  esbuild: true
  maplibre-gl: set this to true or false
  simple-git-hooks: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@iconify-json/carbon@1.2.23'
  - '@types/node@25.9.1'
shellEmulator: true
# eslint-disable-next-line pnpm/yaml-enforce-settings
trustPolicy: off
