/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/blocked': RouteRecordInfo<
      '/blocked',
      '/blocked',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/files/': RouteRecordInfo<
      '/files/',
      '/files',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/others': RouteRecordInfo<
      '/settings/others',
      '/settings/others',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/page': RouteRecordInfo<
      '/settings/page',
      '/settings/page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/security': RouteRecordInfo<
      '/settings/security',
      '/settings/security',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/upload': RouteRecordInfo<
      '/settings/upload',
      '/settings/upload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/status': RouteRecordInfo<
      '/status',
      '/status',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/upload': RouteRecordInfo<
      '/upload',
      '/upload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
      pathParamNames:
        | 'all'
    }
    'src/pages/blocked.vue': {
      routes:
        | '/blocked'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/files/index.vue': {
      routes:
        | '/files/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/others.vue': {
      routes:
        | '/settings/others'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/page.vue': {
      routes:
        | '/settings/page'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/security.vue': {
      routes:
        | '/settings/security'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/upload.vue': {
      routes:
        | '/settings/upload'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/status.vue': {
      routes:
        | '/status'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/upload.vue': {
      routes:
        | '/upload'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
